<a href="https://colab.research.google.com/github/happyendingddd/happyendingddd.github.io/blob/master/GANgRNA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import TensorFlow and other libraries

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [3]:
import glob
import numpy as np
from tensorflow.keras import layers
import matplotlib.pyplot as plt
import time

### 加载和准备数据集

In [ ]:
train_gRNA=

### 生成器

In [ ]:
def make_generator_model():
    model = tf.keras.Sequential()
    model.add(layers.Dense(7*7*256, use_bias=False, input_shape=(100,)))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Reshape((7, 7, 256)))
    assert model.output_shape == (None, 7, 7, 256) # 注意：batch size 没有限制

    model.add(layers.Conv2DTranspose(128, (5, 5), strides=(1, 1), padding='same', use_bias=False))
    assert model.output_shape == (None, 7, 7, 128)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False))
    assert model.output_shape == (None, 14, 14, 64)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh'))
    assert model.output_shape == (None, 28, 28, 1)

    return model

#### 使用（尚未训练的）生成器创建一条gRNA序列

In [ ]:
generator = make_generator_model()

noise = tf.random.normal([1, 100])
generated_gRNA = generator(noise, training=False)

In [3]:
a = ['A','T','C','G']
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
one_hot = encoder.fit_transform(a)
print(one_hot)

[[1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 0 1 0]]


In [4]:
def dense_to_one_hot(labels_dense, num_classes):
   """Convert class labels from scalars to one-hot vectors."""
   num_labels = labels_dense.shape[0]
   index_offset = np.arange(num_labels) * num_classes
   labels_one_hot = np.zeros((num_labels, num_classes))
   labels_one_hot.flat[index_offset + labels_dense.ravel()] = 1
   return labels_one_hot

In [ ]:
labels_dense=['A','T','C','G']
num_classes=[]
labels_one_hot=dense_to_one_hot()

In [6]:
 
class Parent:        # 定义父类
   def myMethod(self):
      print('调用父类方法')
 
class Child(Parent): # 定义子类
   def myMethod(self):
      print('调用子类方法')
 
c = Child()          # 子类实例
c.myMethod()         # 子类调用重写方法

调用子类方法
